name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v28
        with:
          token: ${{ secrets.FLAKE_LOCK_PAT }}
          branch: flake-update
          commit-msg: "flake.lock: update"
          pr-title: "flake.lock: update"
          pr-body: |
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
